// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorData.proto

package org.base.grpc;
import io.grpc.examples.helloworld.HelloReply;
import io.grpc.examples.helloworld.HelloWorldProto;

import com.googlecode.protobuf.format.*;

public class FormatTransfer{
	public static void main(String[] args)
	{
		XmlFormat xmlFormat = new XmlFormat();
		//xmlFormat.printToString(Message m);
		//HelloReply.newBuilder().setMessage("Hello ")
		HelloReply reply = HelloReply.newBuilder().setMessage("Hello").build();
		String str = xmlFormat.printToString(reply.getDefaultInstance());
		str = new HtmlFormat().printToString(reply);
		str = new JsonFormat().printToString(reply);
		str = "";
		
		/*reply.get
		Message someProto = SomeProto.getDefaultInstance();
		XmlFormat xmlFormat = new XmlFormat();
		String asXml = xmlFormat.printToString(someProto);*/
	}
}