// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SimpleClient.proto

package org.base.pb;

public final class SimpleClient {
  private SimpleClient() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequstMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.base.pb.RequstMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes row = 1;</code>
     */
    boolean hasRow();
    /**
     * <code>required bytes row = 1;</code>
     */
    com.google.protobuf.ByteString getRow();

    /**
     * <code>required bool online = 2;</code>
     */
    boolean hasOnline();
    /**
     * <code>required bool online = 2;</code>
     */
    boolean getOnline();

    /**
     * <code>optional int32 len = 3;</code>
     */
    boolean hasLen();
    /**
     * <code>optional int32 len = 3;</code>
     */
    int getLen();
  }
  /**
   * Protobuf type {@code org.base.pb.RequstMessage}
   */
  public  static final class RequstMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.base.pb.RequstMessage)
      RequstMessageOrBuilder {
    // Use RequstMessage.newBuilder() to construct.
    private RequstMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequstMessage() {
      row_ = com.google.protobuf.ByteString.EMPTY;
      online_ = false;
      len_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequstMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              row_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              online_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              len_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.base.pb.SimpleClient.internal_static_org_base_pb_RequstMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.base.pb.SimpleClient.internal_static_org_base_pb_RequstMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.base.pb.SimpleClient.RequstMessage.class, org.base.pb.SimpleClient.RequstMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ROW_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString row_;
    /**
     * <code>required bytes row = 1;</code>
     */
    public boolean hasRow() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes row = 1;</code>
     */
    public com.google.protobuf.ByteString getRow() {
      return row_;
    }

    public static final int ONLINE_FIELD_NUMBER = 2;
    private boolean online_;
    /**
     * <code>required bool online = 2;</code>
     */
    public boolean hasOnline() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool online = 2;</code>
     */
    public boolean getOnline() {
      return online_;
    }

    public static final int LEN_FIELD_NUMBER = 3;
    private int len_;
    /**
     * <code>optional int32 len = 3;</code>
     */
    public boolean hasLen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 len = 3;</code>
     */
    public int getLen() {
      return len_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOnline()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, row_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, online_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, len_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, row_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, online_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, len_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.base.pb.SimpleClient.RequstMessage)) {
        return super.equals(obj);
      }
      org.base.pb.SimpleClient.RequstMessage other = (org.base.pb.SimpleClient.RequstMessage) obj;

      boolean result = true;
      result = result && (hasRow() == other.hasRow());
      if (hasRow()) {
        result = result && getRow()
            .equals(other.getRow());
      }
      result = result && (hasOnline() == other.hasOnline());
      if (hasOnline()) {
        result = result && (getOnline()
            == other.getOnline());
      }
      result = result && (hasLen() == other.hasLen());
      if (hasLen()) {
        result = result && (getLen()
            == other.getLen());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRow()) {
        hash = (37 * hash) + ROW_FIELD_NUMBER;
        hash = (53 * hash) + getRow().hashCode();
      }
      if (hasOnline()) {
        hash = (37 * hash) + ONLINE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getOnline());
      }
      if (hasLen()) {
        hash = (37 * hash) + LEN_FIELD_NUMBER;
        hash = (53 * hash) + getLen();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.base.pb.SimpleClient.RequstMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.base.pb.SimpleClient.RequstMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.base.pb.SimpleClient.RequstMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.base.pb.RequstMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.base.pb.RequstMessage)
        org.base.pb.SimpleClient.RequstMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.base.pb.SimpleClient.internal_static_org_base_pb_RequstMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.base.pb.SimpleClient.internal_static_org_base_pb_RequstMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.base.pb.SimpleClient.RequstMessage.class, org.base.pb.SimpleClient.RequstMessage.Builder.class);
      }

      // Construct using org.base.pb.SimpleClient.RequstMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        row_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        online_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        len_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.base.pb.SimpleClient.internal_static_org_base_pb_RequstMessage_descriptor;
      }

      public org.base.pb.SimpleClient.RequstMessage getDefaultInstanceForType() {
        return org.base.pb.SimpleClient.RequstMessage.getDefaultInstance();
      }

      public org.base.pb.SimpleClient.RequstMessage build() {
        org.base.pb.SimpleClient.RequstMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.base.pb.SimpleClient.RequstMessage buildPartial() {
        org.base.pb.SimpleClient.RequstMessage result = new org.base.pb.SimpleClient.RequstMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.row_ = row_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.online_ = online_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.len_ = len_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.base.pb.SimpleClient.RequstMessage) {
          return mergeFrom((org.base.pb.SimpleClient.RequstMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.base.pb.SimpleClient.RequstMessage other) {
        if (other == org.base.pb.SimpleClient.RequstMessage.getDefaultInstance()) return this;
        if (other.hasRow()) {
          setRow(other.getRow());
        }
        if (other.hasOnline()) {
          setOnline(other.getOnline());
        }
        if (other.hasLen()) {
          setLen(other.getLen());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRow()) {
          return false;
        }
        if (!hasOnline()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.base.pb.SimpleClient.RequstMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.base.pb.SimpleClient.RequstMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString row_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes row = 1;</code>
       */
      public boolean hasRow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public com.google.protobuf.ByteString getRow() {
        return row_;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder setRow(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder clearRow() {
        bitField0_ = (bitField0_ & ~0x00000001);
        row_ = getDefaultInstance().getRow();
        onChanged();
        return this;
      }

      private boolean online_ ;
      /**
       * <code>required bool online = 2;</code>
       */
      public boolean hasOnline() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool online = 2;</code>
       */
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>required bool online = 2;</code>
       */
      public Builder setOnline(boolean value) {
        bitField0_ |= 0x00000002;
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool online = 2;</code>
       */
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000002);
        online_ = false;
        onChanged();
        return this;
      }

      private int len_ ;
      /**
       * <code>optional int32 len = 3;</code>
       */
      public boolean hasLen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 len = 3;</code>
       */
      public int getLen() {
        return len_;
      }
      /**
       * <code>optional int32 len = 3;</code>
       */
      public Builder setLen(int value) {
        bitField0_ |= 0x00000004;
        len_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 len = 3;</code>
       */
      public Builder clearLen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        len_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.base.pb.RequstMessage)
    }

    // @@protoc_insertion_point(class_scope:org.base.pb.RequstMessage)
    private static final org.base.pb.SimpleClient.RequstMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.base.pb.SimpleClient.RequstMessage();
    }

    public static org.base.pb.SimpleClient.RequstMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RequstMessage>
        PARSER = new com.google.protobuf.AbstractParser<RequstMessage>() {
      public RequstMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequstMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequstMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequstMessage> getParserForType() {
      return PARSER;
    }

    public org.base.pb.SimpleClient.RequstMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.base.pb.ResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes row = 1;</code>
     */
    boolean hasRow();
    /**
     * <code>required bytes row = 1;</code>
     */
    com.google.protobuf.ByteString getRow();

    /**
     * <code>repeated string info = 2;</code>
     */
    java.util.List<java.lang.String>
        getInfoList();
    /**
     * <code>repeated string info = 2;</code>
     */
    int getInfoCount();
    /**
     * <code>repeated string info = 2;</code>
     */
    java.lang.String getInfo(int index);
    /**
     * <code>repeated string info = 2;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes(int index);
  }
  /**
   * Protobuf type {@code org.base.pb.ResponseMessage}
   */
  public  static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.base.pb.ResponseMessage)
      ResponseMessageOrBuilder {
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMessage() {
      row_ = com.google.protobuf.ByteString.EMPTY;
      info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              row_ = input.readBytes();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                info_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              info_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          info_ = info_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.base.pb.SimpleClient.internal_static_org_base_pb_ResponseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.base.pb.SimpleClient.internal_static_org_base_pb_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.base.pb.SimpleClient.ResponseMessage.class, org.base.pb.SimpleClient.ResponseMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ROW_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString row_;
    /**
     * <code>required bytes row = 1;</code>
     */
    public boolean hasRow() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes row = 1;</code>
     */
    public com.google.protobuf.ByteString getRow() {
      return row_;
    }

    public static final int INFO_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList info_;
    /**
     * <code>repeated string info = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInfoList() {
      return info_;
    }
    /**
     * <code>repeated string info = 2;</code>
     */
    public int getInfoCount() {
      return info_.size();
    }
    /**
     * <code>repeated string info = 2;</code>
     */
    public java.lang.String getInfo(int index) {
      return info_.get(index);
    }
    /**
     * <code>repeated string info = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes(int index) {
      return info_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRow()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, row_);
      }
      for (int i = 0; i < info_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, info_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, row_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < info_.size(); i++) {
          dataSize += computeStringSizeNoTag(info_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInfoList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.base.pb.SimpleClient.ResponseMessage)) {
        return super.equals(obj);
      }
      org.base.pb.SimpleClient.ResponseMessage other = (org.base.pb.SimpleClient.ResponseMessage) obj;

      boolean result = true;
      result = result && (hasRow() == other.hasRow());
      if (hasRow()) {
        result = result && getRow()
            .equals(other.getRow());
      }
      result = result && getInfoList()
          .equals(other.getInfoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRow()) {
        hash = (37 * hash) + ROW_FIELD_NUMBER;
        hash = (53 * hash) + getRow().hashCode();
      }
      if (getInfoCount() > 0) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.base.pb.SimpleClient.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.base.pb.SimpleClient.ResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.base.pb.ResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.base.pb.ResponseMessage)
        org.base.pb.SimpleClient.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.base.pb.SimpleClient.internal_static_org_base_pb_ResponseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.base.pb.SimpleClient.internal_static_org_base_pb_ResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.base.pb.SimpleClient.ResponseMessage.class, org.base.pb.SimpleClient.ResponseMessage.Builder.class);
      }

      // Construct using org.base.pb.SimpleClient.ResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        row_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.base.pb.SimpleClient.internal_static_org_base_pb_ResponseMessage_descriptor;
      }

      public org.base.pb.SimpleClient.ResponseMessage getDefaultInstanceForType() {
        return org.base.pb.SimpleClient.ResponseMessage.getDefaultInstance();
      }

      public org.base.pb.SimpleClient.ResponseMessage build() {
        org.base.pb.SimpleClient.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.base.pb.SimpleClient.ResponseMessage buildPartial() {
        org.base.pb.SimpleClient.ResponseMessage result = new org.base.pb.SimpleClient.ResponseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.row_ = row_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          info_ = info_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.info_ = info_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.base.pb.SimpleClient.ResponseMessage) {
          return mergeFrom((org.base.pb.SimpleClient.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.base.pb.SimpleClient.ResponseMessage other) {
        if (other == org.base.pb.SimpleClient.ResponseMessage.getDefaultInstance()) return this;
        if (other.hasRow()) {
          setRow(other.getRow());
        }
        if (!other.info_.isEmpty()) {
          if (info_.isEmpty()) {
            info_ = other.info_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInfoIsMutable();
            info_.addAll(other.info_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRow()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.base.pb.SimpleClient.ResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.base.pb.SimpleClient.ResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString row_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes row = 1;</code>
       */
      public boolean hasRow() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public com.google.protobuf.ByteString getRow() {
        return row_;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder setRow(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes row = 1;</code>
       */
      public Builder clearRow() {
        bitField0_ = (bitField0_ & ~0x00000001);
        row_ = getDefaultInstance().getRow();
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          info_ = new com.google.protobuf.LazyStringArrayList(info_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getInfoList() {
        return info_.getUnmodifiableView();
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public int getInfoCount() {
        return info_.size();
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public java.lang.String getInfo(int index) {
        return info_.get(index);
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes(int index) {
        return info_.getByteString(index);
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public Builder setInfo(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfoIsMutable();
        info_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public Builder addInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfoIsMutable();
        info_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public Builder addAllInfo(
          java.lang.Iterable<java.lang.String> values) {
        ensureInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, info_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public Builder clearInfo() {
        info_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string info = 2;</code>
       */
      public Builder addInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInfoIsMutable();
        info_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.base.pb.ResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:org.base.pb.ResponseMessage)
    private static final org.base.pb.SimpleClient.ResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.base.pb.SimpleClient.ResponseMessage();
    }

    public static org.base.pb.SimpleClient.ResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMessage>() {
      public ResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
      return PARSER;
    }

    public org.base.pb.SimpleClient.ResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code org.base.pb.SimpleService}
   */
  public static abstract class SimpleService
      implements com.google.protobuf.Service {
    protected SimpleService() {}

    public interface Interface {
      /**
       * <code>rpc Get(.org.base.pb.RequstMessage) returns (.org.base.pb.ResponseMessage);</code>
       */
      public abstract void get(
          com.google.protobuf.RpcController controller,
          org.base.pb.SimpleClient.RequstMessage request,
          com.google.protobuf.RpcCallback<org.base.pb.SimpleClient.ResponseMessage> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SimpleService() {
        @java.lang.Override
        public  void get(
            com.google.protobuf.RpcController controller,
            org.base.pb.SimpleClient.RequstMessage request,
            com.google.protobuf.RpcCallback<org.base.pb.SimpleClient.ResponseMessage> done) {
          impl.get(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.get(controller, (org.base.pb.SimpleClient.RequstMessage)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.base.pb.SimpleClient.RequstMessage.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.base.pb.SimpleClient.ResponseMessage.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc Get(.org.base.pb.RequstMessage) returns (.org.base.pb.ResponseMessage);</code>
     */
    public abstract void get(
        com.google.protobuf.RpcController controller,
        org.base.pb.SimpleClient.RequstMessage request,
        com.google.protobuf.RpcCallback<org.base.pb.SimpleClient.ResponseMessage> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.base.pb.SimpleClient.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.get(controller, (org.base.pb.SimpleClient.RequstMessage)request,
            com.google.protobuf.RpcUtil.<org.base.pb.SimpleClient.ResponseMessage>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.base.pb.SimpleClient.RequstMessage.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.base.pb.SimpleClient.ResponseMessage.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.base.pb.SimpleClient.SimpleService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void get(
          com.google.protobuf.RpcController controller,
          org.base.pb.SimpleClient.RequstMessage request,
          com.google.protobuf.RpcCallback<org.base.pb.SimpleClient.ResponseMessage> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.base.pb.SimpleClient.ResponseMessage.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.base.pb.SimpleClient.ResponseMessage.class,
            org.base.pb.SimpleClient.ResponseMessage.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.base.pb.SimpleClient.ResponseMessage get(
          com.google.protobuf.RpcController controller,
          org.base.pb.SimpleClient.RequstMessage request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.base.pb.SimpleClient.ResponseMessage get(
          com.google.protobuf.RpcController controller,
          org.base.pb.SimpleClient.RequstMessage request)
          throws com.google.protobuf.ServiceException {
        return (org.base.pb.SimpleClient.ResponseMessage) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.base.pb.SimpleClient.ResponseMessage.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:org.base.pb.SimpleService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_base_pb_RequstMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_base_pb_RequstMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_base_pb_ResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_base_pb_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SimpleClient.proto\022\013org.base.pb\"9\n\rReq" +
      "ustMessage\022\013\n\003row\030\001 \002(\014\022\016\n\006online\030\002 \002(\010\022" +
      "\013\n\003len\030\003 \001(\005\",\n\017ResponseMessage\022\013\n\003row\030\001" +
      " \002(\014\022\014\n\004info\030\002 \003(\t2P\n\rSimpleService\022?\n\003G" +
      "et\022\032.org.base.pb.RequstMessage\032\034.org.bas" +
      "e.pb.ResponseMessageB\010H\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_base_pb_RequstMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_base_pb_RequstMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_base_pb_RequstMessage_descriptor,
        new java.lang.String[] { "Row", "Online", "Len", });
    internal_static_org_base_pb_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_base_pb_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_base_pb_ResponseMessage_descriptor,
        new java.lang.String[] { "Row", "Info", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
